#! /bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1 # https://wiki.archlinux.org/index.php/Java#Applications_not_resizing_with_WM,_menus_immediately_closing
sxhkd &
#polybar --config=$HOME/dotfiles/common/bspwm/polybar myBar &
#/bin/sh $HOME/dotfiles/common/scripts/system.sh
#nm-applet &
#emacs --daemon &
#numlockx &
setxkbmap -layout us -variant altgr-intl -option nodeadkeys caps:swapescape
#sct 3500 &
~/src/monitor-hotplug.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding 30

#bspc config focus_follows_pointer true

bspc config border_width         3
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config remove_unplugged_monitors true
#bspc config remove_disabled_monitors true
#bspc merge_overlapping_monitors true

bspc config normal_border_color
bspc config active_border_color  \#9d2f13
bspc config focused_border_color \#9d2f13
 
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a zatharu state=tiled
bspc rule -a plasmashell state=floating
bspc rule -a Plasma state=floating

sleep 5
seafile-applet &
#sct 3500 &
#~/src/monitor-hotplug.sh &
redshift -t 5000:3500 -l 52.5:13.4 &
